name: ci
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set Up Docker Compose
        run: docker-compose -f ./microservices/docker-compose.yml up -d

      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
        
      - name: Install dependencies
        working-directory: ./microservices/order/
        run: go mod tidy
      
      - name: Test
        working-directory: ./microservices/order/
        run: go test ./... -coverprofile=c.out -covermode=count && go tool cover -func=c.out
